/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReadingRouteImport } from './routes/_authenticated/reading'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedLendingRouteImport } from './routes/_authenticated/lending'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedBooksScanRouteImport } from './routes/_authenticated/books.scan'
import { Route as AuthenticatedBooksNewRouteImport } from './routes/_authenticated/books.new'
import { Route as AuthenticatedBooksImportRouteImport } from './routes/_authenticated/books.import'
import { Route as AuthenticatedBooksBookIdRouteImport } from './routes/_authenticated/books.$bookId'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReadingRoute = AuthenticatedReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLendingRoute = AuthenticatedLendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksScanRoute = AuthenticatedBooksScanRouteImport.update({
  id: '/books/scan',
  path: '/books/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksNewRoute = AuthenticatedBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksImportRoute =
  AuthenticatedBooksImportRouteImport.update({
    id: '/books/import',
    path: '/books/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBooksBookIdRoute =
  AuthenticatedBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/lending': typeof AuthenticatedLendingRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/reading': typeof AuthenticatedReadingRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/books/import': typeof AuthenticatedBooksImportRoute
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/books/scan': typeof AuthenticatedBooksScanRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/lending': typeof AuthenticatedLendingRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/reading': typeof AuthenticatedReadingRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/books/import': typeof AuthenticatedBooksImportRoute
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/books/scan': typeof AuthenticatedBooksScanRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/lending': typeof AuthenticatedLendingRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/reading': typeof AuthenticatedReadingRoute
  '/_authenticated/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/_authenticated/books/import': typeof AuthenticatedBooksImportRoute
  '/_authenticated/books/new': typeof AuthenticatedBooksNewRoute
  '/_authenticated/books/scan': typeof AuthenticatedBooksScanRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/analytics'
    | '/lending'
    | '/library'
    | '/reading'
    | '/books/$bookId'
    | '/books/import'
    | '/books/new'
    | '/books/scan'
    | '/api/public/hooks/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/analytics'
    | '/lending'
    | '/library'
    | '/reading'
    | '/books/$bookId'
    | '/books/import'
    | '/books/new'
    | '/books/scan'
    | '/api/public/hooks/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account'
    | '/_authenticated/analytics'
    | '/_authenticated/lending'
    | '/_authenticated/library'
    | '/_authenticated/reading'
    | '/_authenticated/books/$bookId'
    | '/_authenticated/books/import'
    | '/_authenticated/books/new'
    | '/_authenticated/books/scan'
    | '/api/public/hooks/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reading': {
      id: '/_authenticated/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof AuthenticatedReadingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lending': {
      id: '/_authenticated/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof AuthenticatedLendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/scan': {
      id: '/_authenticated/books/scan'
      path: '/books/scan'
      fullPath: '/books/scan'
      preLoaderRoute: typeof AuthenticatedBooksScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/new': {
      id: '/_authenticated/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AuthenticatedBooksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/import': {
      id: '/_authenticated/books/import'
      path: '/books/import'
      fullPath: '/books/import'
      preLoaderRoute: typeof AuthenticatedBooksImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/$bookId': {
      id: '/_authenticated/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedLendingRoute: typeof AuthenticatedLendingRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedReadingRoute: typeof AuthenticatedReadingRoute
  AuthenticatedBooksBookIdRoute: typeof AuthenticatedBooksBookIdRoute
  AuthenticatedBooksImportRoute: typeof AuthenticatedBooksImportRoute
  AuthenticatedBooksNewRoute: typeof AuthenticatedBooksNewRoute
  AuthenticatedBooksScanRoute: typeof AuthenticatedBooksScanRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedLendingRoute: AuthenticatedLendingRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedReadingRoute: AuthenticatedReadingRoute,
  AuthenticatedBooksBookIdRoute: AuthenticatedBooksBookIdRoute,
  AuthenticatedBooksImportRoute: AuthenticatedBooksImportRoute,
  AuthenticatedBooksNewRoute: AuthenticatedBooksNewRoute,
  AuthenticatedBooksScanRoute: AuthenticatedBooksScanRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
